- lib/oxidized/web/public/css/dataTables.bootstrap.css
- lib/oxidized/web/public/css/dataTables.colVis.css
- lib/oxidized/web/public/scripts/dataTables.colVis.js
- lib/oxidized/web/views/nodes.haml
- lib/oxidized/web/views/sass/oxidized.sass
- Added show / hide columns extention (ip masked by default) 
- Last status is now colored (to read it quickly) and a bubble show in word the status (no_connection is red of course)
- Removed colums for actions and just put it in an "Actions" colums (explain with a bubble what is the action)
----
---
---
> change the basic interface

- lib/oxidized/web/public/css/dataTables.colVis.css
> Remove transparency from button show/hide

- lib/oxidized/web/views/conf_search.haml
- lib/oxidized/web/views/nodes.haml
- lib/oxidized/web/views/sass/oxidized.sass
- lib/oxidized/web/webapp.rb
Permit to search terms in configs and show matching nodes
> Permit to search terms in configs and show matching nodes

- lib/oxidized/web/webapp.rb
Add JSON output for a nodes versions. Allows use of external systems to fetch a list of changes.
> Add version JSON Output

- lib/oxidized/web/views/versions.haml
Add Author and Message Columns to the Nodes versions table
> Author and Message Columns

- lib/oxidized/web/views/node.haml
I find it quite handy having these buttons here, especially for retrying a failed node :)
> Add Node Buttons

- lib/oxidized/web/webapp.rb
Added support for .text and changed.json to split the string to new lines (if it is a string!)
> Change to format = text

- lib/oxidized/web/webapp.rb
Example
=======
get all nodes from super_switch group
---
```
localhost/nodes/group/super_switch
localhost/nodes/group/super_switch.json for JSON output
```
get all Comware nodes
---
```
localhost/nodes/model/Comware 
```
> Added filtered view for nodes

- lib/oxidized/web/views/nodes.haml
I don't know if this is the recommended way to do this but it seems to work OK and it's pretty useful when managing a lot of hosts. Let me know if I should change anything.
> Enables sorting on node status

- lib/oxidized/web/views/conf_search.haml
- lib/oxidized/web/views/default.haml
- lib/oxidized/web/views/diffs.haml
- lib/oxidized/web/views/head.haml
- lib/oxidized/web/views/layout.haml
- lib/oxidized/web/views/migration.haml
- lib/oxidized/web/views/node.haml
- lib/oxidized/web/views/nodes.haml
- lib/oxidized/web/views/stats.haml
- lib/oxidized/web/views/version.haml
- lib/oxidized/web/views/versions.haml
Closes #46.
Refactors some JavaScript and improves the readability of the HAML templates by making the changes suggested in #46.
> Improve HAML readability and minor refactoring

- lib/oxidized/web/views/head.haml
- lib/oxidized/web/views/stats.haml
> Add Sort Support to Stats Page

- lib/oxidized/web/public/scripts/oxidized.js
- lib/oxidized/web/views/stats.haml
> Refactor time converter and switch to lowercase "never"

- Rakefile
- lib/oxidized/web/mig.rb
- lib/oxidized/web/webapp.rb
> Prefer Single Quotes

- lib/oxidized/web/mig.rb
- lib/oxidized/web/webapp.rb
- oxidized-web.gemspec
> Fix Whitespace

- lib/oxidized/web/views/sass/oxidized.sass
> resize oxidized logo

- lib/oxidized/web/public/scripts/oxidized.js
the commit f4a2d9189f50a1c41c8404593bab22a864c06888 forgot to close the `$('#reload').click` function
> fix javascript missing function close

- lib/oxidized/web/webapp.rb
> Fix conf_search JSON output

- lib/oxidized/web/views/diffs.haml
- lib/oxidized/web/views/version.haml
> HTML-escape config from nodes

- .gitignore
- lib/oxidized/web/webapp.rb
- oxidized-web.gemspec
> fix: Fixed UndefinedConversionError in webui

- lib/oxidized/web/webapp.rb
Fixes https://github.com/ytti/oxidized/issues/1132
> UTF-8 fix for view /node/version/diffs

- .gitignore
- oxidized-web.gemspec
> fixed warnings in ruby-2.5

- README.md
> Remove link to not working live demo

- CHANGELOG.md
- lib/oxidized/web/public/weblibs/buttons.bootstrap5.css
- lib/oxidized/web/public/weblibs/buttons.bootstrap5.js
- lib/oxidized/web/public/weblibs/dataTables.bootstrap5.css
- lib/oxidized/web/public/weblibs/dataTables.bootstrap5.js
- lib/oxidized/web/public/weblibs/dataTables.buttons.js
- lib/oxidized/web/public/weblibs/dataTables.js
- package-lock.json
Update datatables and datatables-buttons to the latest versions.
> Update datatables and datatables-buttons

- CHANGELOG.md
- docs/development.md
- lib/oxidized/web/version.rb
- spec/web/node/show_spec.rb
> Release 0.17.1
