lib/oxidized/web/mig.rb
lib/oxidized/web/public/css/dataTables.colVis.css
lib/oxidized/web/public/scripts/script-migration.js
lib/oxidized/web/views/migration.haml
lib/oxidized/web/views/nodes.haml
lib/oxidized/web/views/sass/oxidized.sass
lib/oxidized/web/webapp.rb

Feature to migrate form Rancid to Oxidized.
You can create a first router.db with fake equipment just to access to the web interface, and then click on the migration button and follow the instructions. (You must restart oxidized after of course)
Below the page with the instructions :

Rancid migration Feature

---

lib/oxidized/web/webapp.rb

Hopefully this is the right way to do it, same approach as json above.
As an example of where this is used:
http://127.0.0.1:8080/node/version/view?node=hostname&group=&oid=9b05cda60562b2bcaac569cb507ef31be1df09d1&date=2015-08-19%2012:33:02%20+0100&num=10&format=text
Then gives you plaintext output

Enable ?format=text in URL

---

lib/oxidized/web/views/diffs.haml
lib/oxidized/web/views/sass/oxidized.sass
lib/oxidized/web/views/version.haml

Closes #40.
This PR adds new functionality.  It preserves whitespace from the configs and changes the config output font to a monospace font.  These features improve readability.

update config formatting

---

lib/oxidized/web/webapp.rb

Closes #33.
Convert the search parameter to a Regex and use `String#[]` to look for a match.
I'm also open to searching to see if the string begins and ends with `/` and only converting to a Regex then, but this seems "easier."

Support regexes in searches.

---

lib/oxidized/web/views/layout.haml
lib/oxidized/web/views/stats.haml

Closes #44.
This PR adds a link to the stats page and updates the interface to be more akin to the newer UI.  Screenshot below.

Add Stats Link and Update Interface

---

lib/oxidized/web/public/scripts/oxidized.js
lib/oxidized/web/views/diffs.haml
lib/oxidized/web/views/layout.haml
lib/oxidized/web/views/nodes.haml
lib/oxidized/web/views/version.haml

Closes #16.
Add new javascript file to contain code specific to oxidized-web.
Convert anything set with the `.time` class from UTC to local time.
Unifies absolute time output across web UI.
Requires that the server running oxidized-web to be set to UTC time.
Remove body and include head tags as these may cause issues.

Convert UTC to browser timezone.

---

lib/oxidized/web/views/conf_search.haml
lib/oxidized/web/views/default.haml
lib/oxidized/web/views/diffs.haml
lib/oxidized/web/views/head.haml
lib/oxidized/web/views/layout.haml
lib/oxidized/web/views/migration.haml
lib/oxidized/web/views/node.haml
lib/oxidized/web/views/nodes.haml
lib/oxidized/web/views/stats.haml
lib/oxidized/web/views/version.haml
lib/oxidized/web/views/versions.haml

Closes #47.
Depends on #54.
Adds several new stats, adds highlighting (> 50% failures is warning, >75% failures is critical), changes refresh button to standard Bootstrap styling, displays stats for all nodes (previously only displayed data on hosts that had a failure in last 24 hours).  Removed JavaScript that didn't work to begin with.  Screenshot below.

Add More Stats

---

lib/oxidized/web/views/stats.haml

Closes #60.
Extracts times into their own array.
Uses inject to return the total of the elements.
Divides by number of failures/successes.

fix broken stats implementation

---

lib/oxidized/web/views/conf_search.haml
lib/oxidized/web/views/diffs.haml
lib/oxidized/web/views/layout.haml
lib/oxidized/web/views/node.haml
lib/oxidized/web/views/nodes.haml
lib/oxidized/web/views/stats.haml
lib/oxidized/web/views/version.haml
lib/oxidized/web/views/versions.haml

Closes #55.
Updates all tables to have same responsive, condensed, striped, and hover-enabled styling.
Removes extraneous `body` and `include head`.
Removes unused `#Test` id.
Neatens up code to be placed in row and col divs.

55 feat/bootstrapify

---

lib/oxidized/web/views/head.haml
lib/oxidized/web/views/layout.haml

Resolves an issue for Ruby versions prior to 2.2 that causes symbol keys
with hyphens in them using the new (1.9) hash syntax to generate an
error.
This is done by reverting those symbols to pre-1.9 syntax, as in:
`:'example-key' => 'value'`
See ytti/oxidized-web#84

Change symbol declaration with hyphens.

---

lib/oxidized/web/webapp.rb

default.haml was removed in 391481a, breaking a few routes.
Change the default template to `:text`, which has similar functionality
to the old default.haml.
See ytti/oxidized-web#88

Change default output to text.

---

lib/oxidized/web/public/scripts/oxidized.js
lib/oxidized/web/views/nodes.haml

Adds a new button and hidden div for reloading the node
source on button click.  Div is red if reload was unsuccessful.
Div is green if reload is successful.
Closes ytti/oxidized-web#92

Add button to reload node source

---

lib/oxidized/web/public/scripts/oxidized.js

Use jQuery's `click` function to update the display of timestamps when a pagination button is clicked.
Closes #91.

Fix Paginated Timestamp Display

---

lib/oxidized/web/views/stats.haml

Remove the spurious type of string for the failure_rate column.
Add a better data type for the avg_time column, so it sorts correctly.

Better sorting of the stats page

---

lib/oxidized/web/views/nodes.haml

Makes each model and group into a link on the nodes page to allow for quick filtering of model or group.

Filter by model or group

---

lib/oxidized/web/views/layout.haml

We run oxidized-web behind a reverse proxy and the search fails without this.

Wrap conf_search in url_for()

---

lib/oxidized/web/public/scripts/oxidized.js

Sometimes, the last update date is blank, which results in convertTime() failing:
Uncaught TypeError: Cannot read property '0' of null
at HTMLTableCellElement.<anonymous> (oxidized.js:56)
at Function.each (jquery-2.1.1.min.js:2)
at n.fn.init.each (jquery-2.1.1.min.js:2)
at convertTime (oxidized.js:45)
at HTMLDocument.<anonymous> (oxidized.js:64)
at j (jquery-2.1.1.min.js:2)
at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
at Function.ready (jquery-2.1.1.min.js:2)
at HTMLDocument.I (jquery-2.1.1.min.js:2)
(anonymous) @ oxidized.js:56
each @ jquery-2.1.1.min.js:2
each @ jquery-2.1.1.min.js:2
convertTime @ oxidized.js:45
(anonymous) @ oxidized.js:64
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2
Since this seems …

Fix timezone conversion on page load

---

lib/oxidized/web/views/head.haml

Chrome likes to incorrectly try to translate the page.  This generally doesn't actually accomplish anything, and just screws up the page contents.  Automatic translation really isn't relevant to router configs, so suggest to Chrome to not auto-translate things.

Disable chrome auto-translation

---

lib/oxidized/web/public/scripts/oxidized.js

This should fix the problem with the reload button when Oxidized is deployed under example.com/path. (https://github.com/ytti/oxidized/issues/724)

Corrected relod function to use relative uri

---

lib/oxidized/web/public/scripts/oxidized.js
lib/oxidized/web/views/diffs.haml

Corrected https://github.com/ytti/oxidized-web/issues/121
Also noticed that my last commit in reload button does not work in group view and the script tries to get /oxidized-root/nodes/group/reload.json instead of /oxidized-root/reload.json. This regex should fix this and hope there is no more different views using this same reload button.

Fixes in urls when deployed under non-root path

---

lib/oxidized/web.rb

This splits listen from the right, which allows for listen statements like '[::]:8888'.

Add IPv6 support for the rest / listen parameter

---

oxidized-web.gemspec

It is 'htmlentities' instead of 'htmlentitites'.

fix typo in gemspec

---

lib/oxidized/web/views/diffs.haml
lib/oxidized/web/views/version.haml

Fixes the _leading & trailing_ whitespace between a the `<div>` tag and the actual backed-up configuration.
This seems like it was introduced in #116 & is present in 'oxidized-web-0.9.1'
Fixes issue #132 
My instance looks like the demo running at http://oxidized.arahant.net/ now in term of spacing on diffs and version

Diff ver spacing

---

lib/oxidized/web/views/diffs.haml
lib/oxidized/web/views/version.haml

Fixes https://github.com/ytti/oxidized-web/issues/103
Found the solution [here](https://github.com/haml/haml/issues/296)

Correction of HTML escaping

---

lib/oxidized/web.rb

**Purpose**
if oxidized is run with web interface oxidized cannot be closed by ctrl-c
this PR fixes this problem

bugfix: oxidized cannot exit via ctrl-c

---

oxidized-web.gemspec

Per Puma's [History](https://github.com/puma/puma/blob/master/History.md), Puma 3.12 has been restricted to Ruby 2.2+. As Oxidized currently targets Ruby 2.0+, lock Puma to the more recent suitable version.
Closes ytti/oxidized#1457

pessimistic puma lock on 3.11 as 3.12 requires ruby 2.2+

---

lib/oxidized/web/views/conf_search.haml

XSS vulnerability reported as part of a pentest, this escapes the user input when printing back to the title of the page.
I've had a brief look around and can't find any other user input that's rendered back in to a page.

escape user input to fix XSS "vulnerability"

---

.rubocop.yml
lib/oxidized/web/webapp.rb

This PR changes the `/reload` endpoint to allow a `node`'s name to be passed in and have only that single node reloaded, instead of all nodes.
This supersedes PR https://github.com/ytti/oxidized-web/pull/189, which will be closed in due course

Allow node to be optionally provided to /reload endpoint

---

lib/oxidized/web/public/scripts/oxidized.js

The previous regexp relied on extracting Latin alphabet capital letters and using them as a timezone name and broke on browsers with non-English locales, such as in #194, #186. Extract timezone offset instead.

display timezone as offset

---

lib/oxidized/web/webapp.rb
oxidized-web.gemspec

- since haml 6.0, escape_html: true is default, we need false (old default)
- fixing haml Release to ~> 6.0
- we explicit need PP for node.haml to work (reverting part of commit 079f06a)

Fix haml issues

---

spec/node_spec.rb

The JSON key in the object PUT to /node/next should be "user" and not "author". See https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L79

Change erroneous json key in spec/node_spec.rb

---

CHANGELOG.md
lib/oxidized/web/views/nodes.haml
lib/oxidized/web/views/stats.haml

This PR saves the state of datatables, permitting to permanently store the page length, column visibility or search string in the browser.
Closes #314
Closes #315
Closes #212
Closes #265

Save datatables state

---

CHANGELOG.md
lib/oxidized/web.rb
lib/oxidized/web/webapp.rb

This PR specifies empty vhosts, so that sinatra doesn't block the access to oxidized when using a hostname instead of an ip address.  This fixes #298
It also prepares an extented configuration to specify which vhosts to accept. This part must be done in oxidized, but only after a new version of oxidized-web has been published.

Fix vhosts

---

.gitignore
CHANGELOG.md
lib/oxidized/web.rb
oxidized-web.gemspec
spec/spec_helper.rb
spec/web/node_spec.rb
spec/web/node_version_spec.rb
spec/web/nodes_spec.rb
spec/web/root_spec.rb
spec/web/webapp_spec.rb
spec/web_spec.rb

This is done by starting puma directly.
Close:  #349

Stop puma from renaming the process and reacting on signals
